<?php
// База данных фильмов - RU
$filmsRu = [
    'затмение' => [
        'title' => 'Затмение',
        'year' => '2026',
        'type' => 'Сериал',
        'director' => 'Игорь Каграманов',
        'cast' => 'Дмитрий Миллер, Вероника Устимова, Сергей Юшкевич',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/znam.png',
        'description' => 'Полковник КГБ Шилов должен предотвратить эпидемию черной оспы, которая была занесена в Москву в 1960 году.'
    ],
    'арбатские тайны' => [
        'title' => 'Арбатские тайны',
        'year' => '2021',
        'type' => 'Сериал',
        'director' => 'Зиновий Ройзман, Александр Котт',
        'cast' => 'Ангелина Поплавская, Александр Балуев, Елена Сафонова',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/arbatckietaini1.jpg',
        'description' => 'В основе истории о жизни большой семьи лежит лихая детективная интрига.'
    ],
    'русские горки' => [
        'title' => 'Русские горки',
        'year' => '2019',
        'type' => 'Сериал',
        'director' => 'Алеко Цабадзе',
        'cast' => 'Константин Лавроненко, Карина Андоленко, Екатерина Вилкова',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/russgorki3.jpg',
        'description' => 'История русско-английской семьи с 1945 по 1986 годов.'
    ],
    'отражение радуги' => [
        'title' => 'Отражение радуги',
        'year' => '2019',
        'type' => 'Сериал',
        'director' => 'Тимур Кабулов',
        'cast' => 'Андрей Мерзликин, Наталия Вдовина, Игорь Скляр',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/otrajr.png',
        'description' => 'Криминальный психолог идет по следу искусного манипулятора.'
    ],
    'брак понарошку' => [
        'title' => 'Брак понарошку',
        'year' => '2020',
        'type' => 'Сериал',
        'director' => 'Зиновий Ройзман',
        'cast' => 'Иван Колесников, Мария Шалаева, Валерия Шкирандо',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/brakponaroshku.png',
        'description' => 'Безответственный шоумен и синий чулок заключают фиктивный брак.'
    ],
    'новогодний рейс' => [
        'title' => 'Новогодний рейс',
        'year' => '2014',
        'type' => 'Сериал',
        'director' => 'Нана Джорджадзе',
        'cast' => 'Светлана Ходченкова, Марат Башаров, Сергей Чонишвили',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/novreis.png',
        'description' => 'Благодаря новогодней неразберихе герои меняются городами.'
    ],
    'желание' => [
        'title' => 'Желание',
        'year' => '2009',
        'type' => 'Сериал',
        'director' => 'Сергей Попов',
        'cast' => 'Александр Балуев, Анатолий Белый, Мария Миронова, Ирина Купченко, Екатерина Вилкова, Наталья Рогожкина',
        'episodes' => '2 серии',
        'duration' => '51 мин',
        'image' => 'images/jel.png',
        'description' => 'Вера, Валентина и Виктор — узники любовного треугольника. Виктор и Валентина – преподаватель и студентка, полюбили друг друга и поженились. Но сердцу не прикажешь, и Виктор влюбляется в сестру Валентины Веру. Виктор в замешательстве, он понимает, что чувства к Вере все сильнее овладевают им. Вера тоже без памяти влюбляется в Виктора. Но как же быть с Валей? К тому же выясняется, что она ждет ребенка. Виктор готов объявить Валентине о предстоящем разводе, но Вера внезапно останавливает его: она хочет сохранить семью сестры.'
    ],
    'долгий путь домой' => [
        'title' => 'Долгий путь домой',
        'year' => '2013',
        'type' => 'Сериал',
        'director' => 'Ольга Доброва-Куликова',
        'cast' => 'Дарья Мороз, Елизавета Боярская, Александр Лазарев мл.',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/dolpd.jpg',
        'description' => 'История двух поколений: с начала 80-х до наших дней.'
    ],
    'фурцева' => [
        'title' => 'Фурцева',
        'year' => '2011',
        'type' => 'Сериал',
        'director' => 'Сергей Попов',
        'cast' => 'Александр Домогаров, Ирина Розанова, Валерий Баринов, Вениамин Смехов, Анатолий Белый, Екатерина Вилкова, Татьяна Арнтгольц, Максим Аверин, Нина Усатова, Виктор Сухоруков, Геннадий Хазанов',
        'episodes' => '12 серий',
        'duration' => '51 мин',
        'image' => 'images/furceva.png',
        'description' => 'Сериал посвящен Екатерине Фурцевой, которая прошла путь от сельской «золушки», ткачихи, до «хозяйки Москвы», члена правительства, министра культуры. Работа, карьера, забирающие всю жизнь без остатка и простое женское счастье, стремление к власти и жажда любви, призвание быть лидером, независимость, решительность и желания настоящей женщины, чуткой жены и заботливой матери — как все это может соединиться в одной личности?'
    ],
    'частный заказ' => [
        'title' => 'Частный заказ',
        'year' => '2007',
        'type' => 'Сериал',
        'director' => 'Сергей Ткачёв',
        'cast' => 'Виктория Исакова, Сергей Маховиков, Ирина Розанова, Андрей Краско, Максим Коновалов, Павел Трубинер, Александр Балуев, Юрий Чурсин, Алексей Горбунов, Юрий Степанов',
        'episodes' => '8 серий',
        'duration' => '51 мин',
        'image' => 'images/chastnizakaz.jpg',
        'description' => 'Мария Невзорова — преуспевающая бизнесвумен — оказалась почти беззащитной. Ей не могут помочь ни друзья, ни коллеги, ни даже спецслужбы. Аноним заказал известному телеведущему серию скандальных сюжетов о том, каким же образом Марии, самой обычной девушке из маленького сибирского городка, удалось сделать невероятную карьеру в Москве. Марии надо срочно разгадать тайну частного заказа, иначе в любой момент по чьей-то невидимой указке сенсационные передачи появятся в эфире центральных телеканалов.'
    ],
    'за 5 минут до января' => [
        'title' => 'За 5 минут до января',
        'year' => '2017',
        'type' => 'Сериал',
        'director' => 'Ольга Доброва-Куликова',
        'cast' => 'Дмитрий Миллер, Наталья Рудова, Евгения Добровольская',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/za5minutdojanvar.jpg',
        'description' => 'В новогоднюю ночь в заснеженном Бабаево собрались пять разных людей.'
    ],
    'если любишь прости' => [
        'title' => 'Если любишь — прости',
        'year' => '2013',
        'type' => 'Сериал',
        'director' => 'Ольга Доброва-Куликова',
        'cast' => 'Альберт Филозов, Дмитрий Фрид, Егор Бероев, Илья Любимов, Любовь Толкалина, Светлана Иванова',
        'episodes' => '2 серии',
        'duration' => '52 мин',
        'image' => 'images/eslilubishprosti.jpg',
        'description' => 'Главные герои — судья Юлия Гуляева и её муж шеф-повар Эдик – отмечают десятилетний юбилей свадьбы. Но беда в том, что, заглянув на кухню в разгар торжества, Юлия застает Эдика с официанткой Аней в тот самый момент, когда они выясняют отнюдь не производственные отношения. Эдик умоляет Юлю о прощении: с Аней у него ничего серьезного. Но Юля бескомпромиссный судья не только на работе, но и в жизни. Все надежды на Дашу – младшую сестру Юли, которая вызвалась помогать Эдику и вернуть его в семью. Изменить своим жестким принципам жизнь заставляет Юлю лишь после того, как в её судьбе появляется таинственный незнакомец.'
    ],
    'если нам судьба' => [
        'title' => 'Если нам судьба',
        'year' => '2009',
        'type' => 'Сериал',
        'director' => 'Александр Аравин',
        'cast' => 'Александр Домогаров, Сергей Маховиков, Елена Руфанова, Елена Великанова, Алексей Панин, Татьяна Лютаева, Альберт Филозов',
        'episodes' => '12 серий',
        'duration' => '52 мин',
        'image' => 'images/eslinamsudba.jpg',
        'description' => 'Письмо от неизвестной, которое получает знаменитый артист Александр Власов, неожиданно меняет его жизнь. После таинственной гибели в автокатастрофе дочери Насти он не находил утешения ни в работе, ни в любви, но давняя история, о которой рассказано в письме, вселяет надежду: у Власова есть два взрослых сына-близнеца. Проверить факты помогает подруга Насти, частный детектив Лена Лукова. Её расследование наталкивается на противодействие миллионера Павла Матвеева и гражданской жены Власова Екатерины Добрыниной. Лена Лукова обнаруживает, что Матвеев и Добрынина были связаны когда-то в прошлом и что история близнецов касается не только артиста Власова.'
    ],
    'капитанские дети' => [
        'title' => 'Капитанские дети',
        'year' => '2006',
        'type' => 'Сериал',
        'director' => 'Вячеслав Никифоров',
        'cast' => 'Александра Флоринская, Андрей Толубеев, Андрей Чадов, Вениамин Смехов, Даниэль Ольбрыхский, Елена Корикова, Ивар Калныньш, Игорь Верник, Инна Макарова, Ирина Купченко, Оксана Акиньшина, Ольга Остроумова, Сергей Горобченко, Сергей Маховиков, Эммануил Виторган',
        'episodes' => '19 серий',
        'duration' => '50 мин',
        'image' => 'images/kapdeti.jpg',
        'description' => 'Современная мелодрама, снятая по мотивам романов Анны Берсеневой «Капитанские дети». В её основе сильные чувства и роковые случайности. Действие сериала происходит в наше время. В центре фильма — большая московская семья Гринёвых, представители разных её поколений, которые переживают непохожие, но в одинаковой степени головокружительные любовные истории. Это люди порядочные, надежные, которым свойственна глубоко скрытая, но очень сильная душевная отзывчивость и врождённое благородство. Подсказывая верные ходы, иногда интригуя, испытывая, обманывая, судьба ведёт героев сериала по жизни. За три-четыре года, в течение которых мы наблюдаем Гринёвых, они постепенно меняются, приобретают новые черты характера. Кто-то из них становится мудрее, кто-то — мягче и терпимее, а кто-то понимает, что способен отвечать за близких, и находит в этом счастье.'
    ],
    'найти мужа в большом городе' => [
        'title' => 'Найти мужа в большом городе',
        'year' => '2013',
        'type' => 'Сериал',
        'director' => 'Катя Шагалова',
        'cast' => 'Агния Кузнецова, Алиса Хазанова, Вениамин Смехов, Кирилл Гребенщиков, Любовь Толкалина, Татьяна Лютаева, Ярослав Бойко',
        'episodes' => '4 серии',
        'duration' => '52 мин',
        'image' => 'images/naitimujavbolgorode.jpg',
        'description' => 'Телефильм «Найти мужа в большом городе» — история молодой переводчицы Лизы, которой уже за тридцать, но она все еще не замужем. Хотя женихов вроде бы предостаточно, но нет одного единственного. Решение проблемы берет на себя многоопытная подруга Маша. Она запрещает Лизе «западать» на преуспевающего архитектора Малышева: «не твой формат». Но недостижимый Малышев как раз и нравится Лизе больше всех.'
    ],
    'ты меня слышишь' => [
        'title' => 'Ты меня слышишь?',
        'year' => '2018',
        'type' => 'Сериал',
        'director' => 'Нана Джорджадзе',
        'cast' => 'Виктория Исакова, Константин Лавроненко, Анна Старшенбаум',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/timenyaslishish.jpg',
        'description' => 'Идеальная жена попадает в аварию, и муж видит интимное видео в ее телефоне.'
    ],
    'в тумане' => [
        'title' => 'В тумане',
        'year' => '2012',
        'type' => 'Фильм',
        'director' => 'Сергей Лозница',
        'cast' => 'Владимир Свирский, Владислав Абашин, Кирилл Петров, Никита Перемотов, Сергей Колесов, Юлия Пересильд',
        'episodes' => '',
        'duration' => '2ч 08мин',
        'image' => 'images/vtumane.jpg',
        'description' => 'Белоруссия. 1942 год. Разгар фашистской оккупации и партизанской войны. Недалеко от хутора, где живет путевой обходчик Сущеня, взорван поезд. Невинного Сущеню арестовывают вместе с группой диверсантов, но не казнят, а отпускают на волю. По округе разносится слух о том, что Сущеня – коллаборационист, и партизаны Буров и Войтик приезжают убить предателя. Партизаны ведут приговоренного к смерти в лес, но попадают в засаду, и Сущеня остается один на один со своим смертельно раненным палачом. В глухом лесу, где нет ни чужих, ни своих, где нет границы между предательством и подвигом, Сущеня совершает моральный выбор в аморальных обстоятельствах.'
    ],
    'родственный обмен' => [
        'title' => 'Родственный обмен',
        'year' => '2004',
        'type' => 'Сериал',
        'director' => 'Владимир Котт',
        'cast' => 'Кристина Орбакайте, Марат Башаров, Дмитрий Певцов, Сергей Варчук, Анатолий Кот',
        'episodes' => '8 серий',
        'duration' => '51 мин',
        'image' => 'images/rodstvennii obmen.jpg',
        'description' => 'Действие комедийного сериала начинается в Москве 1977 года. Главные героини Вера и Юля Тимофеевы — близнецы. Они работают медсестрами в поликлинике и мечтают увидеть мир и жить другой, более интересной жизнью. Их мать умерла, а отца они никогда не знали. Фиктивный брак и эмиграция в Израиль дают одной из сестер возможность реализовать свою мечту. Одна уезжает, а другая остается и занимает ее должностное место.'
    ],
    'процесс' => [
        'title' => 'Процесс',
        'year' => '2013',
        'type' => 'Сериал',
        'director' => 'Александр Ефремов',
        'cast' => 'Алена Яковлева, Анна Каменкова, Анна Снаткина, Игорь Верник, Павел Баршак, Эмилия Спивак',
        'episodes' => '4 серии',
        'duration' => '52 мин',
        'image' => 'images/proces.png',
        'description' => 'Телефильм «Процесс» — это история разведенных родителей, которые «делят» пятилетнюю дочь. Мать - Марго - думает только о своей женской карьере и хочет увезти дочь в Америку к новому мужу. Отец - Сергей - пытается оспаривать решение суда. На стороне Марго выступает знаменитый адвокат Махновский — любовник Марго, - и бороться с ним бессмысленно. Правда, главная героиня фильма, молодой адвокат Екатерина Логинова, считает иначе.'
    ],
    'непрощенные' => [
        'title' => 'Непрощенные',
        'year' => '2009',
        'type' => 'Фильм',
        'director' => 'Клим Шипенко',
        'cast' => 'Александр Демидов, Анатолий Лобоцкий, Борис Хвошнянский, Владимир Симонов, Евгений Пронин, Константин Демидов, Константин Соловьев, Ксения Буравская, Михаил Бабичев, Олег Долин, Ольга Ломоносова, Татьяна Васильева',
        'episodes' => '',
        'duration' => '1ч 47мин',
        'image' => 'images/neprozshennie.png',
        'description' => 'Их шестеро: Андрей, Лекс, Сильвер, Лис, Дин и Дина – молодые, отчаянные, готовые на любой риск. Алиса – хозяйка злачного заведения — предлагает им хорошие деньги, чтобы отомстить за Владика - несбывшуюся любовь всей её жизни. Но «деньги явно нелегкие» — честно предупреждает Алиса. Почему они соглашаются? У каждого свой путь к решению. Поначалу герои даже не знают друг друга. Но лихие, криминальные судьбы постепенно сближают их, пока все вместе они не приходят к Алисе. Они не жалеют, что жизнь сложилась так, а не иначе. Им нравится свобода на грани фола. Они не ищут прощения — даже перед лицом смерти.'
    ],
    'как бы не так' => [
        'title' => 'Как бы не так',
        'year' => '2003',
        'type' => 'Сериал',
        'director' => 'Максим Пежемский',
        'cast' => 'Евгений Сидихин, Николай Чиндяйкин, Дина Корзун, Сергей Чонишвили, Михаил Горевой, Геннадий Назаров, Павел Деревянко',
        'episodes' => '2 серии',
        'duration' => '52 мин',
        'image' => 'images/kakbinetak.jpg',
        'description' => 'Действие сериала происходит в небольшом и на первый взгляд спокойном городке. Криминальный авторитет Старик перевозит крупную сумму денег и попадает под обстрел. Раненого Старика находит врач Марина, обычная женщина средних лет. Но доброе дело оборачивается крупными неприятностями: женщину подозревают в том, что именно она украла чемодан денег. Только телохранитель авторитета Коля Лось не верит, что Марина причастна к преступлению. Сериал является экранизацией одноименного романа Татьяны Поляковой.'
    ],
    'частный сыск' => [
        'title' => 'Сувенир от парфюмера',
        'year' => '2010',
        'type' => 'Сериал',
        'director' => 'Денис Червяков',
        'cast' => 'Сергей Шакуров, Александр Устюгов, Кирилл Сафонов, Татьяна Черкасова, Ирина Алферова, Магомед Костоев',
        'episodes' => '4 серии',
        'duration' => '51 мин',
        'image' => 'images/suvenirotvarfumera.jpg',
        'description' => 'Полковник внешней разведки в отставке Валерий Петрович Ходасевич отправляется в приморский городок Костров на помощь падчерице Татьяне, которая оказалась в эпицентре смертельно опасной криминальной истории. Офис крупной рекламной компании, которой она руководит, был разгромлен, а ее коллега бесследно исчез. Вскоре выясняется, что преступники связаны с незаконной торговлей оружием и готовы на все ради достижения своих целей. Снято по мотивам произведений Анны и Сергея Литвиновых.'
    ],
    'серебряный бор' => [
        'title' => 'Серебряный бор',
        'year' => '2017',
        'type' => 'Сериал',
        'director' => 'Зиновий Ройзман',
        'cast' => 'Мария Шукшина, Сергей Маховиков, Марк Богатырев',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/sereb-bor.jpg',
        'description' => 'Семейная сага с конца 70-х до начала 80-х.'
    ],
    'строптивая мишень' => [
        'title' => 'Строптивая мишень',
        'year' => '2004',
        'type' => 'Сериал',
        'director' => 'Юлия Колесник',
        'cast' => 'Андрей Краско, Наталия Антонова, Максим Коновалов, Юрий Цурило, Алиса Гребенщикова, Наталья Коляканова, Никита Тюнин, Андрей Финягин, Михаил Кешишьян',
        'episodes' => '4 серии',
        'duration' => '51 мин',
        'image' => 'images/stroptovayamishen2.jpg',
        'description' => 'В небольшом провинциальном городишке Дина жила спокойной и размеренной жизнью. Но её муж Олег, который был связан с криминальными структурами и носил кличку Студент, втянул её в самые настоящие неприятности. Теперь Дина вынуждена спасаться бегством от преследующих её бандитов во главе с Эдичкой. Но судьбе было угодно свести главную героиню с человеком, который станет ей настоящим другом и опорой в жизни, и в котором она найдет нового возлюбленного.'
    ],
    'служба доверия' => [
        'title' => 'Служба доверия',
        'year' => '2007',
        'type' => 'Сериал',
        'director' => 'Елена Николаева',
        'cast' => 'Татьяна Догилева, Евгения Симонова, Мария Шукшина',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/clujbadoveria.jpg',
        'description' => 'Кризисная служба готова помогать людям круглосуточно.'
    ],
    'кроткая' => [
        'title' => 'Кроткая',
        'year' => '2017',
        'type' => 'Фильм',
        'director' => 'Сергей Лозница',
        'cast' => 'Василина Маковцева, Валериу Андрюцэ, Сергей Колесов, Дмитрий Быковский, Лия Ахеджакова, Алиса Кравцова, Константин Итунин, Николай Коляда, Сергей Федоров, Александр Замураев',
        'episodes' => '',
        'duration' => '2ч 40мин',
        'image' => 'images/krotkaya.jpg',
        'description' => 'Молодая женщина по пути на свидание к арестованному мужу встречает различных героев своего времени: от полицейских и правозащитников до проституток и бродяг.'
    ],
    'требуется няня' => [
        'title' => 'Требуется няня',
        'year' => '2005',
        'type' => 'Фильм',
        'director' => 'Лариса Садилова',
        'cast' => 'Марина Зубанова, Ирина Шипова, Алексей Макаров, Виктория Исакова, Раиса Рязанова, Валерий Баринов, Шерхан Ходжаев, Евгения Пресникова, Инна Алабина, Владимир Вышлов',
        'episodes' => '',
        'duration' => '1ч 44мин',
        'image' => 'images/trebuetsyanyna.png',
        'description' => 'Молодые супруги Вера и Андрей живут в достатке и на первый взгляд счастливо. Их загородный дом расположен в элитном поселке, работа приносит приличный доход, и молодая пара даже позволяет себе иметь прислугу. На их участке не покладая рук трудятся строители, а на хозяйстве — всегда исполнительная домработница тетя Маша. Осталось подумать о детях, и супруги ищут няню для непоседливой дочери Али. По рекомендации в их дом приходит милая девушка Галя. Фильм стал призером «Кинотавра», а также номинировался на премию «Ника».'
    ],
    'нелегал' => [
        'title' => 'Нелегал',
        'year' => '2005',
        'type' => 'Фильм',
        'director' => 'Юрий Лебедев, Борис Фрумин',
        'cast' => 'Алексей Серебряков, Ольга Албанова, Анатолий Петров, Екатерина Решетникова, Сергей Уманов, Артур Харитоненко, Светлана Обидина, Дмитрий Сутырин, Хельга Филиппова',
        'episodes' => '',
        'duration' => '1ч 34мин',
        'image' => 'images/nelegal.jpg',
        'description' => 'Семидесятые. Холодная война в самом разгаре, СССР и Запад ведут напряженную борьбу за секретные сведения друг о друге. Советские спецслужбы хотят избавить своих курьеров от слишком пристального внимания таможенников в ленинградском аэропорту. Решено внедрить на ленинградскую таможню сотрудника ГРУ. Для выполнения такого ответственного задания Центр возвращает в Советский Союз своего опытного агента, который уже много лет работает в Хельсинки, и на Родине о нем никто не знает. Теперь, чтобы отработать свою новую легенду и справиться с заданием Центра, герою снова приходиться стать нелегалом. Только на этот раз — нелегалом в своей собственной стране…'
    ],
    '2 цвета страсти' => [
        'title' => 'Два цвета страсти',
        'year' => '2007',
        'type' => 'Сериал',
        'director' => 'Каринэ Фолиянц',
        'cast' => 'Антон Феоктистов, Эльвира Болгова, Евгения Лоза, Юрий Беляев, Игорь Лифанов, Сергей Баталов, Роман Мадянов, Альберт Филозов',
        'episodes' => '10 серий',
        'duration' => '52 мин',
        'image' => 'images/2cvetastrasti.jpg',
        'description' => 'Небольшой приморский городок. Только что окончивший школу с золотой медалью красавчик Максим устраивается на первую работу — учителем английского к детям богатого местного ресторатора Тимошина. Но вместо того, чтобы повторять неправильные глаголы на языке Шекспира, он не на шутку увлекается женой работодателя — Верой. Тут-то и начинаются основные трудности. В результате интриг новоиспеченный Жюльен Сорель окажется в Москве, где быстро понравится, как фармацевтическому королю Долгопятову, так и его юной дочери Саше. Максиму предстоит сделать трудный выбор.'
    ],
    'механическая сюита' => [
        'title' => 'Механическая сюита',
        'year' => '2002',
        'type' => 'Фильм',
        'director' => 'Дмитрий Месхиев',
        'cast' => 'Сергей Гармаш, Константин Хабенский, Михаил Пореченков, Ирина Розанова, Сергей Маковецкий, Евгения Добровольская, Александр Баширов',
        'episodes' => '',
        'duration' => '1ч 40мин',
        'image' => 'images/mehsiuta.jpg',
        'description' => 'Коля из патентного отдела на выходных скончался в Лыково. Его тело решили вывозить за счет предприятия. В Лыково отправили непьющего Маркеранца и делового Митягина. Последний предложил выпить в вагоне-ресторане, что повлекло за собой цепь невероятных событий, расследовать которые поручают деревенскому следователю.'
    ],
    'желтый карлик' => [
        'title' => 'Желтый карлик',
        'year' => '2001',
        'type' => 'Фильм',
        'director' => 'Дмитрий Астрахан',
        'cast' => 'Александр Абдулов, Елена Проклова, Анна Легчилова',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/jeltiikarlik.jpg',
        'description' => 'Отец жениха готов на все, чтобы сорвать неравный брак.'
    ],
    'алмазы на десерт' => [
        'title' => 'Алмазы на десерт',
        'year' => '2006',
        'type' => 'Сериал',
        'director' => 'Александр Мохов',
        'cast' => 'Юрий Беляев, Сергей Баталов, Александр Феклистов, Марина Могилевская, Дарья Калмыкова',
        'episodes' => '3 серии',
        'duration' => '51 мин',
        'image' => 'images/almasi-na-desert.jpg',
        'description' => 'В небольшом провинциальном городке работает подпольный цех, занимающийся огранкой алмазов. За этим стоит местный криминальный авторитет — Павлик, владелец ресторана. С ним в связке работает его школьный приятель — Валера. Павлик хочет ввести в свой бизнес и другого своего одноклассника — Юрия, который недавно вышел из колонии, отсидев срок по ложному обвинению. Юра соглашается занять должность главного инженера в компании Павла, не подозревая, что попал в опасную ловушку. Сериал снят по мотивам романа Татьяны Поляковой «Миллионерша желает познакомиться».'
    ],
    'за кулисами' => [
        'title' => 'За кулисами',
        'year' => '2002',
        'type' => 'Фильм',
        'director' => 'Игорь Талпа',
        'cast' => 'Марина Зудина, Сергей Виноградов, Татьяна Васильева',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/zakulisami.jpg',
        'description' => 'Вдова режиссера расследует его убийство.'
    ],
    'алхимики' => [
        'title' => 'Алхимики',
        'year' => '2002',
        'type' => 'Фильм',
        'director' => 'Дмитрий Астрахан',
        'cast' => 'Юрий Стоянов, Илья Олейников, Виктор Сухоруков',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/alhimiki.jpg',
        'description' => 'Фантастическая комедия о лихих 90-х.'
    ]
];

// База данных фильмов - EN
$filmsEn = [
    'затмение' => [
        'title' => 'Eclipse',
        'year' => '2026',
        'type' => 'TV Series',
        'director' => 'Igor Kagramanov',
        'cast' => 'Dmitry Miller, Veronika Ustimova, Sergey Yushkevich',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/znam.png',
        'description' => 'KGB Colonel Shilov must prevent a smallpox epidemic brought to Moscow in 1960.'
    ],
    'арбатские тайны' => [
        'title' => 'Arbat Mysteries',
        'year' => '2021',
        'type' => 'TV Series',
        'director' => 'Zinovy Roizman, Alexander Kott',
        'cast' => 'Angelina Poplavskaya, Alexander Baluev, Elena Safonova',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/arbatckietaini1.jpg',
        'description' => 'A daring detective intrigue at the heart of a large family story.'
    ],
    'русские горки' => [
        'title' => 'Russian Roller Coaster',
        'year' => '2019',
        'type' => 'TV Series',
        'director' => 'Aleko Tsabadze',
        'cast' => 'Konstantin Lavronenko, Karina Andolenko, Ekaterina Vilkova',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/russgorki3.jpg',
        'description' => 'The story of a Russian-English family from 1945 to 1986.'
    ],
    'отражение радуги' => [
        'title' => 'Reflection of the Rainbow',
        'year' => '2019',
        'type' => 'TV Series',
        'director' => 'Timur Kabulov',
        'cast' => 'Andrey Merzlikin, Natalia Vdovina, Igor Sklyar',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/otrajr.png',
        'description' => 'Criminal psychologist follows a skilled manipulator.'
    ],
    'брак понарошку' => [
        'title' => 'Fake Marriage',
        'year' => '2020',
        'type' => 'TV Series',
        'director' => 'Zinovy Roizman',
        'cast' => 'Ivan Kolesnikov, Maria Shalaeva, Valeria Shkirando',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/brakponaroshku.png',
        'description' => 'Irresponsible showman and plain Jane enter a fake marriage.'
    ],
    'новогодний рейс' => [
        'title' => 'New Year Flight',
        'year' => '2014',
        'type' => 'TV Series',
        'director' => 'Nana Dzhordzhadze',
        'cast' => 'Svetlana Khodchenkova, Marat Basharov, Sergey Chonishvili',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/novreis.png',
        'description' => 'Heroes swap cities on New Year\'s Eve and find love.'
    ],
    'желание' => [
        'title' => 'Desire',
        'year' => '2009',
        'type' => 'TV Series',
        'director' => 'Sergey Popov',
        'cast' => 'Alexander Baluev, Anatoly Bely, Maria Mironova, Irina Kupchenko, Ekaterina Vilkova, Natalia Rogozhkina',
        'episodes' => '2 episodes',
        'duration' => '51 min',
        'image' => 'images/jel.png',
        'description' => 'Vera, Valentina, and Victor are prisoners of a love triangle. Victor and Valentina — teacher and student — fell in love and got married. But the heart cannot be commanded, and Victor falls in love with Valentina\'s sister Vera. Victor is confused, he understands that feelings for Vera are increasingly overwhelming him. Vera also falls madly in love with Victor. But what about Valya? Moreover, it turns out she is expecting a child. Victor is ready to announce the upcoming divorce to Valentina, but Vera suddenly stops him: she wants to preserve her sister\'s family.'
    ],
    'долгий путь домой' => [
        'title' => 'Long Way Home',
        'year' => '2013',
        'type' => 'TV Series',
        'director' => 'Olga Dobrova-Kulikova',
        'cast' => 'Darya Moroz, Elizaveta Boyarskaya, Alexander Lazarev Jr.',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/dolpd.jpg',
        'description' => 'The story of two generations: from the early 80s to our days.'
    ],
    'фурцева' => [
        'title' => 'Furtseva',
        'year' => '2011',
        'type' => 'TV Series',
        'director' => 'Sergey Popov',
        'cast' => 'Alexander Domogarov, Irina Rozanova, Valery Barinov, Veniamin Smekhov, Anatoly Bely, Ekaterina Vilkova, Tatyana Arntgolts, Maxim Averin, Nina Usatova, Viktor Sukhorukov, Gennady Khazanov',
        'episodes' => '12 episodes',
        'duration' => '51 min',
        'image' => 'images/furceva.png',
        'description' => 'The series is dedicated to Ekaterina Furtseva, who went from a rural "Cinderella", a weaver, to the "mistress of Moscow", a member of the government, Minister of Culture. Work, career, taking up one\'s whole life without a trace, and simple female happiness, the desire for power and the thirst for love, the calling to be a leader, independence, determination, and the desires of a real woman, a sensitive wife, and a caring mother — how can all this be combined in one personality?'
    ],
    'частный заказ' => [
        'title' => 'Private Order',
        'year' => '2007',
        'type' => 'TV Series',
        'director' => 'Sergey Tkachev',
        'cast' => 'Victoria Isakova, Sergey Makhovikov, Irina Rozanova, Andrey Krasko, Maxim Konovalov, Pavel Trubiner, Alexander Baluev, Yuri Chursin, Alexey Gorbanov, Yuri Stepanov',
        'episodes' => '8 episodes',
        'duration' => '51 min',
        'image' => 'images/chastnizakaz.jpg',
        'description' => 'Maria Nevzorova — a successful businesswoman — turned out to be almost defenseless. Neither friends, nor colleagues, nor even special services can help her. An anonymous person ordered a famous TV presenter to make a series of scandalous stories about how Maria, the most ordinary girl from a small Siberian town, managed to make an incredible career in Moscow. Maria needs to urgently solve the mystery of the private order, otherwise at any moment, at someone\'s invisible command, sensational programs will appear on the air of central TV channels.'
    ],
    'за 5 минут до января' => [
        'title' => '5 Minutes Before January',
        'year' => '2017',
        'type' => 'TV Series',
        'director' => 'Olga Dobrova-Kulikova',
        'cast' => 'Dmitry Miller, Natalia Rudova, Evgenia Dobrovolskaya',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/za5minutdojanvar.jpg',
        'description' => 'Five different people meet on New Year\'s Eve in snowy Babaevo.'
    ],
    'если любишь прости' => [
        'title' => 'If You Love, Forgive',
        'year' => '2013',
        'type' => 'TV Series',
        'director' => 'Olga Dobrova-Kulikova',
        'cast' => 'Albert Filozov, Dmitry Frid, Egor Beroev, Ilya Lyubimov, Lyubov Tolkalina, Svetlana Ivanova',
        'episodes' => '2 episodes',
        'duration' => '52 min',
        'image' => 'images/eslilubishprosti.jpg',
        'description' => 'The main characters are Yulia Gulyaeva, a respected judge, and her husband Edik, a successful chef. As they celebrate their tenth wedding anniversary, Yulia\'s seemingly perfect life falls apart when she catches Edik with a young waitress. Edik begs for forgiveness, insisting that the affair means nothing. But Yulia is uncompromising — not only in the courtroom, but also in her personal life. The family\'s last hope lies with Dasha, Yulia\'s younger sister, who is determined to reconcile the couple. Life forces Yulia to change her rigid principles only after a mysterious stranger appears in her fate.'
    ],
    'если нам судьба' => [
        'title' => 'If It\'s Our Fate',
        'year' => '2009',
        'type' => 'TV Series',
        'director' => 'Alexander Aravin',
        'cast' => 'Alexander Domogarov, Sergey Makhovikov, Elena Rufanova, Elena Velikanova, Alexey Panin, Tatyana Lyutaeva, Albert Filozov',
        'episodes' => '12 episodes',
        'duration' => '52 min',
        'image' => 'images/eslinamsudba.jpg',
        'description' => 'A letter from an unknown woman unexpectedly changes the life of celebrated actor Alexander Vlasov. Ever since the tragic death of his daughter Nastya in a car accident, Vlasov has been unable to find solace either in his work or in his personal life. But the story revealed in the mysterious letter gives him new hope: he may have two adult twin sons. Private detective Lena Lukova helps verify the facts. Her investigation runs into opposition from millionaire Pavel Matveev and Vlasov\'s common-law wife Ekaterina Dobrynina. Lena discovers that Matveev and Dobrynina were connected in the past and that the twins\' story concerns not only artist Vlasov.'
    ],
    'капитанские дети' => [
        'title' => 'Captain\'s Children',
        'year' => '2006',
        'type' => 'TV Series',
        'director' => 'Vyacheslav Nikiforov',
        'cast' => 'Alexandra Florinskaya, Andrey Tolubeyev, Andrey Chadov, Veniamin Smekhov, Daniel Olbrychski, Elena Korikova, Ivar Kalnins, Igor Vernik, Inna Makarova, Irina Kupchenko, Oksana Akinshina, Olga Ostroumova, Sergey Gorobchenko, Sergey Makhovikov, Emmanuel Vitorgan',
        'episodes' => '19 episodes',
        'duration' => '50 min',
        'image' => 'images/kapdeti.jpg',
        'description' => 'A contemporary romantic drama based on the novels by Anna Berseneva. At its heart are powerful emotions, unexpected twists of fate, and life-changing coincidences. The series follows the Grinyov family, whose members represent several generations. Each of them experiences a unique yet equally captivating love story. Over the course of several years, the characters gradually change and grow, learning valuable lessons about themselves and those closest to them.'
    ],
    'найти мужа в большом городе' => [
        'title' => 'Finding a Husband in a Big City',
        'year' => '2013',
        'type' => 'TV Series',
        'director' => 'Katya Shagalova',
        'cast' => 'Agniya Kuznetsova, Alisa Khazanova, Veniamin Smekhov, Kirill Grebenshchikov, Lyubov Tolkalina, Tatiana Lyutaeva, Yaroslav Boyko',
        'episodes' => '4 episodes',
        'duration' => '52 min',
        'image' => 'images/naitimujavbolgorode.jpg',
        'description' => 'The TV film tells the story of Lisa, a young translator in her thirties who is still not married. Although there are plenty of potential suitors in her life, she has not yet found "the one." Her experienced friend Masha decides to take matters into her own hands. She forbids Lisa from getting involved with the successful architect Malyshev, insisting he is "not her type." However, it is precisely the unattainable Malyshev who appeals to Lisa the most.'
    ],
    'ты меня слышишь' => [
        'title' => 'Do You Hear Me?',
        'year' => '2018',
        'type' => 'TV Series',
        'director' => 'Nana Dzhordzhadze',
        'cast' => 'Victoria Isakova, Konstantin Lavronenko, Anna Starshenbaum',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/timenyaslishish.jpg',
        'description' => 'Ideal wife gets into an accident, husband sees intimate video on her phone.'
    ],
    'в тумане' => [
        'title' => 'In the Fog',
        'year' => '2012',
        'type' => 'Feature Film',
        'director' => 'Sergei Loznitsa',
        'cast' => 'Vladimir Svírsky, Vladislav Abashin, Kirill Petrov, Nikita Peremotov, Sergey Kolesov, Yulia Peresild',
        'episodes' => '',
        'duration' => '2h 08min',
        'image' => 'images/vtumane.jpg',
        'description' => 'Belarus, 1942. The height of fascist occupation and partisan warfare. Near the farmstead where railway worker Sushenya lives, a train has been blown up. The innocent Sushenya is arrested along with a group of saboteurs, but not executed — instead, he is released. A rumor spreads that Sushenya is a collaborator, and partisans Burov and Voytik come to kill the traitor. The partisans lead the condemned man into the forest, but fall into an ambush, and Sushenya is left alone with his mortally wounded executioner. In the deep forest, where there are neither strangers nor friends, where there is no boundary between betrayal and heroism, Sushenya makes a moral choice in amoral circumstances.'
    ],
    'родственный обмен' => [
        'title' => 'Relative Exchange',
        'year' => '2004',
        'type' => 'TV Series',
        'director' => 'Vladimir Kott',
        'cast' => 'Kristina Orbakaite, Marat Basharov, Dmitry Pevtsov, Sergey Varchuk, Anatoly Kot',
        'episodes' => '8 episodes',
        'duration' => '51 min',
        'image' => 'images/rodstvennii obmen.jpg',
        'description' => 'The action of the comedy series begins in Moscow in 1977. The main heroines, Vera and Yulia Timofeeva, are twins. They work as nurses in a polyclinic and dream of seeing the world and living a different, more interesting life. Their mother has died, and they never knew their father. A fictitious marriage and emigration to Israel give one of the sisters the opportunity to realize her dream. One leaves, and the other stays and takes her place.'
    ],
    'процесс' => [
        'title' => 'The Trial',
        'year' => '2013',
        'type' => 'TV Series',
        'director' => 'Alexander Efremov',
        'cast' => 'Alena Yakovleva, Anna Kamenkova, Anna Snatkina, Igor Vernik, Pavel Barshak, Emilia Spivak',
        'episodes' => '4 episodes',
        'duration' => '52 min',
        'image' => 'images/proces.png',
        'description' => 'The TV film tells the story of divorced parents who are fighting over custody of their five-year-old daughter. The mother, Margo, is focused on her career and plans to take her daughter to the United States to live with her new husband. The father, Sergey, is trying to challenge the court\'s decision. On Margo\'s side stands the famous lawyer Makhnovsky, her lover — against whom it seems impossible to win. However, the main protagonist, a young lawyer Ekaterina Loginova, believes otherwise.'
    ],
    'непрощенные' => [
        'title' => 'The Unforgiven',
        'year' => '2009',
        'type' => 'Feature Film',
        'director' => 'Klim Shipenko',
        'cast' => 'Alexander Demidov, Anatoly Lobotsky, Boris Khvoshnyansky, Vladimir Simonov, Evgeny Pronin, Konstantin Demidov, Konstantin Solovyov, Ksenia Buravskaya, Mikhail Babichev, Oleg Dolin, Olga Lomonosova, Tatyana Vasilyeva',
        'episodes' => '',
        'duration' => '1h 47min',
        'image' => 'images/neprozshennie.png',
        'description' => 'There are six of them: Andrey, Lex, Silver, Lis, Dean, and Dina — young, fearless, and willing to take any risk. Alisa, the owner of a seedy establishment, offers them a substantial sum of money to help her take revenge for Vladik — the unfulfilled love of her life. Drawn to a freedom that exists on the edge of danger, they live by their own rules and seek no forgiveness — not even in the face of death.'
    ],
    'как бы не так' => [
        'title' => 'Not Quite',
        'year' => '2003',
        'type' => 'TV Series',
        'director' => 'Maxim Pezhemsky',
        'cast' => 'Evgeny Sidikhin, Nikolay Chindyaykin, Dina Korzun, Sergey Chonishvili, Mikhail Gorevoy, Gennady Nazarov, Pavel Derevyanko',
        'episodes' => '2 episodes',
        'duration' => '52 min',
        'image' => 'images/kakbinetak.jpg',
        'description' => 'The series is set in a small town that appears peaceful and quiet at first glance. A local crime boss known as Starik is transporting a large sum of money when he comes under attack. Wounded, he is found by Marina, an ordinary middle-aged doctor. However, her good deed soon turns into a nightmare: Marina becomes the prime suspect in the theft of a suitcase full of cash. Only Starik\'s bodyguard, Kolya Los, refuses to believe that she is involved in the crime. The series is based on the novel of the same name by Tatyana Polyakova.'
    ],
    'частный сыск' => [
        'title' => 'A Gift from the Perfumer',
        'year' => '2010',
        'type' => 'TV Series',
        'director' => 'Denis Chervyakov',
        'cast' => 'Sergey Shakurov, Alexander Ustyugov, Kirill Safonov, Tatyana Cherkasova, Irina Alferova, Magomed Kostoev',
        'episodes' => '4 episodes',
        'duration' => '51 min',
        'image' => 'images/suvenirotvarfumera.jpg',
        'description' => 'Retired foreign intelligence Colonel Valery Petrovich Khodasevich goes to the seaside town of Kostrov to help his stepdaughter Tatyana, who has found herself at the epicenter of a deadly dangerous criminal story. The office of the large advertising company she runs has been ransacked, and her colleague has disappeared without a trace. It soon turns out that the criminals are involved in illegal arms trafficking and are ready to do anything to achieve their goals. Based on the works of Anna and Sergey Litvinov.'
    ],
    'серебряный бор' => [
        'title' => 'Silver Pine Forest',
        'year' => '2017',
        'type' => 'TV Series',
        'director' => 'Zinovy Roizman',
        'cast' => 'Maria Shukshina, Sergey Makhovikov, Mark Bogatyrev',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/sereb-bor.jpg',
        'description' => 'Family saga from the late 70s to early 80s.'
    ],
    'строптивая мишень' => [
        'title' => 'Stubborn Target',
        'year' => '2004',
        'type' => 'TV Series',
        'director' => 'Yulia Kolesnik',
        'cast' => 'Andrey Krasko, Natalia Antonova, Maxim Konovalov, Yuri Tsyrilo, Alisa Grebenshchikova, Natalia Kolyakanova, Nikita Tyunin, Andrey Finyagin, Mikhail Keshishyan',
        'episodes' => '4 episodes',
        'duration' => '51 min',
        'image' => 'images/stroptovayamishen2.jpg',
        'description' => 'In a small provincial town, Dina lived a calm and measured life. But her husband Oleg, who was connected with criminal structures and nicknamed Student, dragged her into real trouble. Now Dina is forced to flee from the bandits pursuing her, led by Edichka. But fate willed that the main heroine meet a person who will become a true friend and support in life, and in whom she will find a new lover.'
    ],
    'служба доверия' => [
        'title' => 'Trust Service',
        'year' => '2007',
        'type' => 'TV Series',
        'director' => 'Elena Nikolaeva',
        'cast' => 'Tatyana Dogileva, Evgenia Simonova, Maria Shukshina',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/clujbadoveria.jpg',
        'description' => 'Crisis service ready to help people around the clock.'
    ],
    'кроткая' => [
        'title' => 'A Gentle Creature',
        'year' => '2017',
        'type' => 'Feature Film',
        'director' => 'Sergei Loznitsa',
        'cast' => 'Vasilina Makovtseva, Valeriu Andriută, Sergey Kolesov, Dmitry Bykovsky, Liya Akhedzhakova, Alisa Kravtsova, Konstantin Itunin, Nikolai Kolyada, Sergey Fedorov, Alexander Zamuraev',
        'episodes' => '',
        'duration' => '2h 40min',
        'image' => 'images/krotkaya.jpg',
        'description' => 'A young woman on her way to visit her imprisoned husband encounters various heroes of her time: from police officers and human rights activists to prostitutes and vagrants.'
    ],
    'требуется няня' => [
        'title' => 'Nanny Needed',
        'year' => '2005',
        'type' => 'Feature Film',
        'director' => 'Larisa Sadilova',
        'cast' => 'Marina Zubanova, Irina Shipova, Alexey Makarov, Victoria Isakova, Raisia Ryazanova, Valery Barinov, Sherhan Khodzhaev, Evgenia Presnikova, Inna Alabina, Vladimir Vyshlov',
        'episodes' => '',
        'duration' => '1h 44min',
        'image' => 'images/trebuetsyanyna.png',
        'description' => 'Young spouses Vera and Andrey live in prosperity and seemingly happily. Their country house is located in an elite village, work brings a decent income, and the young couple can even afford to have servants. Builders work tirelessly on their plot, and on the farm — always efficient housekeeper Aunt Masha. It remains to think about children, and the spouses are looking for a nanny for their restless daughter Ali. On recommendation, a sweet girl Galya comes to their house. The film became a prize-winner of Kinotavr and was also nominated for the Nika Award.'
    ],
    'нелегал' => [
        'title' => 'Illegal',
        'year' => '2005',
        'type' => 'Feature Film',
        'director' => 'Yuri Lebedev, Boris Frumin',
        'cast' => 'Alexey Serebryakov, Olga Albanova, Anatoly Petrov, Ekaterina Reshetnikova, Sergey Umanov, Artur Kharitonenko, Svetlana Obidina, Dmitry Sutyurin, Helga Filippova',
        'episodes' => '',
        'duration' => '1h 34min',
        'image' => 'images/nelegal.jpg',
        'description' => 'The seventies. The Cold War is in full swing, the USSR and the West are engaged in a tense struggle for each other\'s secrets. Soviet special services want to rid their couriers of the too close attention of customs officers at the Leningrad airport. It is decided to embed a GRU officer at the Leningrad customs. To carry out such a responsible task, the Center returns to the Soviet Union its experienced agent, who has been working in Helsinki for many years, and no one knows about him in the Motherland. Now, to work out his new legend and cope with the Center\'s task, the hero has to become an illegal again. Only this time — an illegal in his own country…'
    ],
    '2 цвета страсти' => [
        'title' => 'Two Colors of Passion',
        'year' => '2007',
        'type' => 'TV Series',
        'director' => 'Karine Foliyants',
        'cast' => 'Anton Feoktistov, Elvira Bolgova, Evgenia Loza, Yuri Belyaev, Igor Lifanov, Sergey Batalov, Roman Madyanov, Albert Filozov',
        'episodes' => '10 episodes',
        'duration' => '52 min',
        'image' => 'images/2cvetastrasti.jpg',
        'description' => 'A small seaside town. Maxim, who has just graduated from school with a gold medal, gets his first job — teaching English to the children of a rich local restaurateur Timoshin. But instead of repeating irregular verbs in Shakespeare\'s language, he seriously becomes infatuated with his employer\'s wife — Vera. This is where the main difficulties begin. As a result of intrigues, the newly minted Julien Sorel will find himself in Moscow, where he will quickly please both the pharmaceutical king Dolgopyatov and his young daughter Sasha. Maxim faces a difficult choice.'
    ],
    'механическая сюита' => [
        'title' => 'Mechanical Suite',
        'year' => '2002',
        'type' => 'Feature Film',
        'director' => 'Dmitry Meskhiev',
        'cast' => 'Sergey Garmash, Konstantin Khabensky, Mikhail Porechenkov, Irina Rozanova, Sergey Makovetsky, Evgeniya Dobrovolskaya, Alexander Bashirov',
        'episodes' => '',
        'duration' => '1h 40min',
        'image' => 'images/mehsiuta.jpg',
        'description' => 'Kolya, an employee of the Patent Department, dies unexpectedly in the village of Lykovo over the weekend. The company decides to arrange and pay for the transportation of his body. Two colleagues are sent to handle the matter: Markerants, a strict teetotaler, and Mityagin, a practical man of business. When Mityagin suggests a drink in the train\'s dining car, a series of bizarre and unpredictable events is set in motion. Untangling the mystery falls to a local rural investigator.'
    ],
    'желтый карлик' => [
        'title' => 'Yellow Dwarf',
        'year' => '2001',
        'type' => 'Feature Film',
        'director' => 'Dmitry Astrakhan',
        'cast' => 'Alexander Abdulov, Elena Proklova, Anna Legchilova',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/jeltiikarlik.jpg',
        'description' => 'The groom\'s father is ready to do anything to thwart an unequal marriage.'
    ],
    'алмазы на десерт' => [
        'title' => 'Diamonds for Dessert',
        'year' => '2006',
        'type' => 'TV Series',
        'director' => 'Alexander Mokhov',
        'cast' => 'Yuri Belyaev, Sergey Batalov, Alexander Feklistov, Marina Mogilevskaya, Darya Kalmykova',
        'episodes' => '3 episodes',
        'duration' => '51 min',
        'image' => 'images/almasi-na-desert.jpg',
        'description' => 'In a small provincial town, an underground workshop is engaged in diamond cutting. Behind this is the local crime boss Pavlik, the owner of a restaurant. His school friend Valera works with him. Pavlik wants to bring another of his classmates into his business — Yuri, who recently got out of the colony after serving time on a false charge. Yura agrees to take the position of chief engineer in Pavel\'s company, not suspecting that he has fallen into a dangerous trap. The series is based on the novel by Tatyana Polyakova "Millionairess Wants to Meet".'
    ],
    'за кулисами' => [
        'title' => 'Behind the Scenes',
        'year' => '2002',
        'type' => 'Feature Film',
        'director' => 'Igor Talpa',
        'cast' => 'Marina Zudina, Sergey Vinogradov, Tatyana Vasilyeva',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/zakulisami.jpg',
        'description' => 'Director\'s widow investigates his murder.'
    ],
    'алхимики' => [
        'title' => 'Alchemists',
        'year' => '2002',
        'type' => 'Feature Film',
        'director' => 'Dmitry Astrakhan',
        'cast' => 'Yuri Stoyanov, Ilya Oleynikov, Viktor Sukhorukov',
        'episodes' => '',
        'duration' => '',
        'image' => 'images/alhimiki.jpg',
        'description' => 'Fantastic comedy about the wild 90s.'
    ]
];
?>